### ISSUE TITLE
python3 -m bot error

### ISSUE THREAD

**Issue by jisa8438** [aryanvikash/Youtube-Downloader-Bot#56]
![image](https://github.com/aryanvikash/Youtube-Downloader-Bot/assets/39065858/9f235324-e2f1-4cd2-9294-04ab9a84e50c)

**Comment by santosadrian** [comment]
same here...

(johndoubot) user@localhost:~/Youtube-Downloader-Bot$ python3 -m bot
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/johndoubot/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/johndoubot/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Youtube-Downloader-Bot/bot/__main__.py", line 2, in <module>
    import config
  File "/home/user/Youtube-Downloader-Bot/config.py", line 4, in <module>
    APP_ID = int(os.environ.get("censored_app-id"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Please help
